### ISSUE TITLE
Purple colour on navigation drawer menu item press

### ISSUE THREAD

**Issue by rpmargetts** [sillsdev/appbuilder-pwa#229] opened 2023-05-13 14:48 UTC
When you press a menu item in the navigation drawer, it turns purple. It should be a grey colour instead.

**Comment by chrisvire** [comment] 2023-05-14 02:55
Duplicate of #205

**Closed by chrisvire** 2023-05-14 02:55 UTC
Labels: bug

**Comment by chrisvire** [comment] 2023-06-05 19:37
With the update to the dependencies, the color is not purple anymore but dark gray. So I need to verify with Richard about the color.
