### ISSUE TITLE
Book and chapter labels on toolbar too small

### ISSUE THREAD

**Issue by rpmargetts** [sillsdev/appbuilder-pwa#227] opened 2023-05-13 14:44 UTC
The book name and chapter number on the toolbar look too small. They need to be in a slightly bigger font size.

Please try and match the size they have in the Android app.

**Comment by chrisvire** [comment] 2023-05-14 22:21
I suspect that this is caused by SAB defining font-size in the User Interface styles in "sp" which is for Android.  

For some reason, this hasn't been a problem for desktop and they looked ok.  Looking in devtools, it has been ignoring the the "24sp" size and using the DaisyUI default of 0.875rem.

We will need to convert font-sizes defined in sp into another appropriate unit for the web.  This is going to be tricky in that sp is dependent on the dpi of the device:

```
px = sp * dpi / 160
```

For the web, it should be based on em or rem.  We are currently defining all of our units in rem.

@rpmargetts  Do you have any thoughts on this?

Here is the conversation that I had with ChatGPT about it (hopefully you can see it):

https://chat.openai.com/c/fa464325-39f3-4b24-9c3c-9ca5da21b54a

**Comment by Caleb-Parks** [comment] 2023-06-01 20:57
Turns out that the sp value is stored not in the text-size field but rather in the font-size field, which is a property parsed in convertConfig.ts's parseStyles() function.

**Comment by chrisvire** [comment] 2023-06-13 03:39
Fixed by #246

**Closed by chrisvire** 2023-06-13 03:39 UTC
Labels: bug
